import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Generated by `flutter_rust_bridge_codegen generate` (see
// flutter_rust_bridge.yaml). These files do not exist until you run codegen.
import 'src/rust/api/aegis.dart';
import 'src/rust/frb_generated.dart';

import 'background.dart';
import 'biometrics.dart';
import 'config.dart';
import 'device_integrity.dart';
import 'disguise.dart';
import 'notifications.dart';
import 'screen_security.dart';
import 'secure_store.dart';
import 'updater.dart';

const _seedKey = 'aegis.master_seed';
const _vaultKey = 'aegis.seed_vault'; // base64 password-encrypted seed
const _duressVaultKey = 'aegis.duress_vault'; // vault for the decoy seed
const _modeKey = 'aegis.mode'; // 'network' | 'relay:<addr>' | 'memory'
const _stateKey = 'aegis.state_blob'; // base64 sessions + contacts + history
const _decoyStateKey = 'aegis.decoy_state'; // separate state for the decoy account
const _notesKey = 'aegis.notes_blob'; // encrypted local-only notes (real account)
const _decoyNotesKey = 'aegis.decoy_notes'; // encrypted notes for the decoy account
const _nodeKey = 'aegis.node_enabled';
const _bootstrapKey = 'aegis.bootstrap'; // comma-separated user-added nodes
const _ownNodesOnlyKey = 'aegis.own_nodes_only'; // route only through my nodes
const _proxyModeKey = 'aegis.proxy_mode'; // 'off' | 'tor' | 'socks5' | 'chain'
const _proxyHostKey = 'aegis.proxy_host'; // host:port for socks5 / chain mode
const _proxyUserKey = 'aegis.proxy_user';
const _proxyPassKey = 'aegis.proxy_pass';
const _proxyTorFirstKey = 'aegis.proxy_tor_first'; // chain order: Tor→SOCKS5 vs SOCKS5→Tor

/// The default Tor SOCKS5 endpoint (Orbot on Android).
const _torEndpoint = '127.0.0.1:9050';
const _favNodesKey = 'aegis.favorite_nodes'; // node ids the user starred
const _notifyKey = 'aegis.notifications'; // show a notification on new messages
const _nodeVerifiedKey = 'aegis.node_verified'; // completed the sync/verify wait
const _secureScreenKey = 'aegis.secure_screen'; // block screenshots (default on)
const _backgroundKey = 'aegis.background'; // 24/7 background service (default on)
const _disguiseKey = 'aegis.disguise'; // launcher icon/name: default|calculator|notes|weather
const _autoLockMinKey = 'aegis.autolock_minutes'; // 0 = off, else re-lock after N min
const _lockOnBgKey = 'aegis.lock_on_background'; // re-lock the moment the app backgrounds
const _wipeAttemptsKey = 'aegis.wipe_after_attempts'; // 0 = off, else wipe after N wrong unlocks
const _failedUnlocksKey = 'aegis.failed_unlocks'; // persisted wrong-password counter

/// How long a first-time node must stay up to be "verified" before it can be
/// toggled freely — a deliberate confirmation-of-intent + anti-abuse delay.
const nodeSyncDuration = Duration(minutes: 20);

/// Thrown when node mode can't be enabled (e.g. only a local/private IP).
class NodeModeError implements Exception {
  final String message;
  NodeModeError(this.message);
  @override
  String toString() => message;
}

/// Thrown by [AegisEngineController.unlock] when the failed-attempt limit is hit
/// and the account is wiped; the UI should route to onboarding.
class AccountWipedException implements Exception {}

/// How this device reaches the network.
enum ConnMode { network, relay, memory }

/// What's on disk at launch: no account, a plaintext seed, or a password vault.
enum AccountState { none, plaintext, locked }

/// Owns the one Rust [AegisEngine] and the app's chat state. Screens listen to
/// this and call into it. The seed is stored **encrypted at rest** — sealed in
/// the password vault when an app password is set, else in keystore-backed
/// secure storage — and all crypto stays in Rust. Chat state and notes are also
/// encrypted on disk with seed-derived keys.
class AegisEngineController extends ChangeNotifier {
  AegisEngine? _engine;
  Timer? _pollTimer;
  Timer? _coverTimer;
  final _rng = Random.secure();
  String _mode = 'network';
  bool _nodeEnabled = false;
  NodeInfo? _node;
  List<String> _userBootstrap = const [];
  bool _ownNodesOnly = false; // route only through the user's own nodes
  String _proxyMode = 'off'; // 'off' | 'tor' | 'socks5' | 'chain'
  String _proxyHost = ''; // host:port for socks5 / chain mode
  String _proxyUser = '';
  String _proxyPass = '';
  bool _proxyTorFirst = false; // chain: Tor→SOCKS5 (true) vs SOCKS5→Tor (false)
  Uint8List? _seed; // kept in memory to rebuild the engine on a node toggle
  bool _anonReceive = false; // network + node mode: the engine runs its own node
  bool _passwordSet = false; // the seed is protected by an app-lock password
  bool _hasDuress = false; // a duress/decoy password is configured
  bool _isDecoy = false; // the currently booted account is the decoy, not the real one
  bool _notify = false; // show a notification when a message arrives
  bool _secureScreen = true; // block screenshots / screen recording (default on)
  bool _background = true; // keep receiving in the background (default on)
  String _disguise = 'default'; // launcher disguise: default|calculator|notes|weather
  int _autoLockMinutes = 0; // 0 = off
  bool _lockOnBackground = false;
  int _wipeAfterAttempts = 0; // 0 = off
  int _failedUnlocks = 0; // persisted wrong-password count
  bool _locked = false; // session locked (engine torn down, needs re-unlock)
  bool _nodeVerified = false; // finished the one-time 20-min sync/verify
  Timer? _syncTimer; // ticks during the sync wait
  DateTime? _syncCompleteAt; // when the sync wait finishes (null if not syncing)
  Set<String> _favNodes = {}; // node ids the user starred

  /// Whether the one-time node verification (20-min sync) is done; after this,
  /// node mode toggles instantly.
  bool get nodeVerified => _nodeVerified;

  /// Time left in the sync/verify wait, or null if not currently syncing.
  Duration? get nodeSyncRemaining {
    final at = _syncCompleteAt;
    if (at == null) return null;
    final left = at.difference(DateTime.now());
    return left.isNegative ? Duration.zero : left;
  }

  /// Whether new-message notifications are on.
  bool get notificationsEnabled => _notify;

  /// Turn new-message notifications on/off (persisted). Enabling asks the OS for
  /// permission; if denied, the setting stays off.
  Future<void> setNotificationsEnabled(bool on) async {
    if (on && !await Notifications.requestPermission()) {
      on = false;
    }
    _notify = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_notifyKey, on);
    notifyListeners();
  }

  /// Whether an app-lock password currently protects the seed on disk.
  bool get hasPassword => _passwordSet;

  /// Whether a duress/decoy password is set (a second password that opens an
  /// empty decoy account instead of the real one).
  bool get hasDuress => _hasDuress;

  /// Whether the currently running account is the decoy (entered via the duress
  /// password), not the real identity. Screens hide sensitive settings in this
  /// mode so an attacker can't tell it apart from a fresh, real account.
  bool get isDecoy => _isDecoy;

  /// The state blob key for whichever account is booted (real vs decoy), so the
  /// decoy's chats never touch the real account's saved state.
  String get _activeStateKey => _isDecoy ? _decoyStateKey : _stateKey;

  /// The encrypted-notes blob key for the booted account (real vs decoy).
  String get _activeNotesKey => _isDecoy ? _decoyNotesKey : _notesKey;

  bool _notesLocked = false; // notes blob is password-protected, not yet unlocked

  /// The private notes (local-only "Notes" chat), oldest first.
  List<Note> notes() => _engine?.notes() ?? const [];

  /// Whether the notes are behind a separate password and still locked this
  /// session (the UI shows an unlock prompt).
  bool get notesLocked => _notesLocked;

  /// Whether a separate notes password is configured (locked, or set in memory).
  bool get notesHasPassword =>
      _notesLocked || (_engine?.notesPasswordSet() ?? false);

  /// Unlock password-protected notes for this session. Returns false on a wrong
  /// password.
  Future<bool> unlockNotes(String password) async {
    final engine = _engine;
    if (engine == null) return false;
    final prefs = await SharedPreferences.getInstance();
    final b64 = prefs.getString(_activeNotesKey);
    if (b64 == null) return false;
    try {
      engine.unlockNotes(password: password, blob: base64Decode(b64));
      _notesLocked = false;
      notifyListeners();
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Set (or change) the notes password (double-layer encryption). Requires the
  /// notes to be unlocked. Persisted immediately.
  Future<void> setNotesPassword(String password) async {
    _engine?.setNotesPassword(password: password);
    await _persistNotes();
    notifyListeners();
  }

  /// Remove the notes password (back to seed-only encryption).
  Future<void> removeNotesPassword() async {
    _engine?.removeNotesPassword();
    await _persistNotes();
    notifyListeners();
  }

  /// Panic-wipe just the notes: clear them and delete the stored blob.
  Future<void> panicWipeNotes() async {
    _engine?.wipeNotes();
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_activeNotesKey);
    _notesLocked = false;
    notifyListeners();
  }

  /// Add a private note (local only, encrypted at rest). Persisted immediately.
  Future<void> addNote(String text) async {
    _engine?.addNote(text: text);
    await _persistNotes();
    notifyListeners();
  }

  /// Edit note [id].
  Future<void> editNote(BigInt id, String text) async {
    _engine?.editNote(id: id, text: text);
    await _persistNotes();
    notifyListeners();
  }

  /// Delete note [id].
  Future<void> deleteNote(BigInt id) async {
    _engine?.deleteNote(id: id);
    await _persistNotes();
    notifyListeners();
  }

  /// Save the encrypted notes blob (ciphertext) to this account's storage.
  Future<void> _persistNotes() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final blob = engine.exportNotes();
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_activeNotesKey, base64Encode(blob));
    } catch (e) {
      debugPrint('notes save failed: $e');
    }
  }

  /// Load this account's notes blob. A password-protected blob stays locked
  /// (the Notes screen prompts for the notes password); a seed-only blob loads.
  Future<void> _restoreNotes() async {
    final engine = _engine;
    if (engine == null) return;
    _notesLocked = false;
    final prefs = await SharedPreferences.getInstance();
    final b64 = prefs.getString(_activeNotesKey);
    if (b64 == null) return;
    final blob = base64Decode(b64);
    if (notesBlobEncrypted(blob: blob)) {
      _notesLocked = true; // needs the notes password before it can be read
      return;
    }
    try {
      engine.restoreNotes(blob: blob);
    } catch (e) {
      debugPrint('notes restore failed (starting empty): $e');
    }
  }

  /// The nodes this client currently knows from the gossiped directory.
  List<NodeSummary> networkNodes() => _engine?.networkNodes() ?? const [];

  /// Node ids the user has starred as preferred.
  Set<String> get favoriteNodes => _favNodes;

  /// Star / unstar a node; persisted. (Preferred nodes will drive custom-node
  /// routing once that mode lands.)
  Future<void> toggleFavoriteNode(String id) async {
    if (!_favNodes.remove(id)) _favNodes.add(id);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setStringList(_favNodesKey, _favNodes.toList());
    notifyListeners();
  }

  /// The bootstrap nodes actually used. Normally the compiled-in set
  /// (`--dart-define`) plus any the user added, de-duplicated. When "only my
  /// nodes" is on and the user has added at least one, **only** the user's nodes
  /// are used, so all traffic bootstraps and routes through their own
  /// infrastructure.
  List<String> get _bootstrap => _ownNodesOnly && _userBootstrap.isNotEmpty
      ? _userBootstrap.toList()
      : {...kBootstrapNodes, ..._userBootstrap}.toList();

  /// The nodes the user has added by hand (host:port).
  List<String> get myNodes => List.unmodifiable(_userBootstrap);

  /// Whether the app routes exclusively through the user's own nodes.
  bool get ownNodesOnly => _ownNodesOnly;

  /// The proxy mode: `off`, `tor`, `socks5`, or `chain` (SOCKS5 + Tor).
  String get proxyMode => _proxyMode;

  /// The custom SOCKS5 endpoint (`host:port`) for `socks5` / `chain` mode.
  String get proxyHost => _proxyHost;
  String get proxyUser => _proxyUser;
  String get proxyPass => _proxyPass;

  /// In `chain` mode, whether Tor is the first hop (`Tor → SOCKS5`) rather than
  /// the last (`SOCKS5 → Tor`).
  bool get proxyTorFirst => _proxyTorFirst;

  ProxyHop get _socksHop => ProxyHop(
        proxy: _proxyHost,
        username: _proxyUser.isEmpty ? null : _proxyUser,
        password: _proxyPass.isEmpty ? null : _proxyPass,
      );
  ProxyHop get _torHop =>
      ProxyHop(proxy: _torEndpoint, username: null, password: null);

  /// Push the current proxy choice into the Rust transport (process-wide). Both
  /// the mixnet and the provider connection honour it. Safe to call before a
  /// connection exists.
  void _applyProxy() {
    switch (_proxyMode) {
      case 'tor':
        setProxyChain(chain: [_torHop]);
      case 'socks5':
        setProxyChain(chain: _proxyHost.isEmpty ? [] : [_socksHop]);
      case 'chain':
        // app → SOCKS5 → Tor by default, or Tor first if chosen.
        setProxyChain(
          chain: _proxyHost.isEmpty
              ? [_torHop]
              : (_proxyTorFirst ? [_torHop, _socksHop] : [_socksHop, _torHop]),
        );
      default:
        setProxyChain(chain: []);
    }
  }

  /// Change the proxy: `off`, `tor`, `socks5`, or `chain` (SOCKS5 + Tor). For
  /// `socks5`/`chain`, pass the SOCKS5 `host:port` and optional credentials;
  /// `torFirst` sets the chain order. Persisted, applied to the transport, then
  /// the engine reconnects so it takes effect immediately.
  Future<void> updateProxy(
    String mode, {
    String host = '',
    String user = '',
    String pass = '',
    bool torFirst = false,
  }) async {
    _proxyMode = mode;
    _proxyHost = host.trim();
    _proxyUser = user;
    _proxyPass = pass;
    _proxyTorFirst = torFirst;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_proxyModeKey, _proxyMode);
    await prefs.setString(_proxyHostKey, _proxyHost);
    await prefs.setString(_proxyUserKey, _proxyUser);
    await prefs.setString(_proxyPassKey, _proxyPass);
    await prefs.setBool(_proxyTorFirstKey, _proxyTorFirst);
    _applyProxy();
    await _reconnect();
  }

  /// Add a bootstrap node (`host:port`) the user typed, then reconnect through
  /// the new set. Ignores a duplicate or blank entry.
  Future<void> addMyNode(String hostPort) async {
    final node = hostPort.trim();
    if (node.isEmpty || _userBootstrap.contains(node)) return;
    _userBootstrap = [..._userBootstrap, node];
    final prefs = await SharedPreferences.getInstance();
    await prefs.setStringList(_bootstrapKey, _userBootstrap);
    await _reconnect();
  }

  /// Remove one of the user's nodes and reconnect.
  Future<void> removeMyNode(String hostPort) async {
    if (!_userBootstrap.contains(hostPort)) return;
    _userBootstrap = _userBootstrap.where((n) => n != hostPort).toList();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setStringList(_bootstrapKey, _userBootstrap);
    await _reconnect();
  }

  /// Turn "route only through my nodes" on/off (persisted) and reconnect.
  Future<void> setOwnNodesOnly(bool on) async {
    _ownNodesOnly = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_ownNodesOnlyKey, on);
    await _reconnect();
  }

  /// Rebuild the engine on the current seed with the current bootstrap set,
  /// restoring saved state. Used when the node set or routing changes.
  Future<void> _reconnect() async {
    final seed = _seed;
    if (seed == null) {
      notifyListeners();
      return;
    }
    await _start(seed);
    final prefs = await SharedPreferences.getInstance();
    final blob = prefs.getString(_activeStateKey);
    if (blob != null) {
      try {
        _engine!.restoreStateEncrypted(blob: base64Decode(blob));
      } catch (_) {}
    }
    notifyListeners();
  }

  /// Whether the app knows any node to bootstrap from (else it can't use the
  /// mixnet and the user must add one).
  bool get hasBootstrap => _bootstrap.isNotEmpty;

  bool get isReady => _engine != null;
  String get myAegisId => _engine!.myAegisId();
  Uint8List get myBundle => _engine!.myBundle();

  /// Whether this device is also running an opt-in mix node.
  bool get nodeEnabled => _nodeEnabled;

  /// The running node's address + id, if node mode is on.
  NodeInfo? get node => _node;

  /// Whether receive is going through the mixnet (anonymous), not a direct poll.
  bool get anonReceive => _anonReceive;

  /// A human label for the current connection mode.
  String get connectionLabel {
    if (_mode == 'network') {
      return _anonReceive
          ? 'Mixnet · anonymous send + receive'
          : 'Mixnet · anonymous send';
    }
    if (_mode.startsWith('relay:')) return 'Relay ${_mode.substring(6)}';
    return 'Offline (in-memory)';
  }

  /// The Rust bridge may be initialized only once per process. Guard it so a
  /// second [boot] (e.g. the startup-error Retry) doesn't throw
  /// "Should not initialize flutter_rust_bridge twice".
  static bool _rustInited = false;

  static Future<void> _ensureRustInit() async {
    if (_rustInited) return;
    try {
      await RustLib.init();
    } catch (e) {
      // Already initialized by an earlier boot in this process — that's fine;
      // rethrow anything else.
      if (!e.toString().contains('initialize flutter_rust_bridge twice')) {
        rethrow;
      }
    }
    _rustInited = true;
  }

  /// Initialize the Rust bridge (safe to call repeatedly) and apply the
  /// screenshot-block setting (secure by default) before any screen shows.
  Future<void> init() async {
    await _ensureRustInit();
    final prefs = await SharedPreferences.getInstance();
    // Apply the proxy first of all — before anything can open a connection.
    _proxyMode = prefs.getString(_proxyModeKey) ?? 'off';
    _proxyHost = prefs.getString(_proxyHostKey) ?? '';
    _proxyUser = prefs.getString(_proxyUserKey) ?? '';
    _proxyPass = prefs.getString(_proxyPassKey) ?? '';
    _proxyTorFirst = prefs.getBool(_proxyTorFirstKey) ?? false;
    _applyProxy();
    _secureScreen = prefs.getBool(_secureScreenKey) ?? true;
    // Native onCreate already set the flag on; only need to relax it if the user
    // turned the setting off.
    if (!_secureScreen) await ScreenSecurity.setSecure(false);
    // Keep receiving in the background by default (opt-out).
    _background = prefs.getBool(_backgroundKey) ?? true;
    if (_background) {
      await BackgroundService.start();
    }
    _disguise = prefs.getString(_disguiseKey) ?? 'default';
    _autoLockMinutes = prefs.getInt(_autoLockMinKey) ?? 0;
    _lockOnBackground = prefs.getBool(_lockOnBgKey) ?? false;
    _wipeAfterAttempts = prefs.getInt(_wipeAttemptsKey) ?? 0;
    _failedUnlocks = prefs.getInt(_failedUnlocksKey) ?? 0;
    // Check for a newer release in the background (never blocks startup).
    unawaited(checkForUpdate());
    // Best-effort root/emulator check (device hardening §1.4).
    unawaited(_checkIntegrity());
  }

  DeviceIntegrity? _integrity;

  /// The result of the root/emulator check (null until it has run). `flagged`
  /// is true if anything worth warning about was detected.
  DeviceIntegrity? get deviceIntegrity => _integrity;

  Future<void> _checkIntegrity() async {
    _integrity = await DeviceIntegrity.check();
    if (_integrity!.flagged) notifyListeners();
  }

  // --- auto-lock & wipe-after-failed-attempts -------------------------------

  /// Minutes of inactivity / background before the app re-locks (0 = off).
  int get autoLockMinutes => _autoLockMinutes;

  /// Whether the app re-locks the instant it goes to the background.
  bool get lockOnBackground => _lockOnBackground;

  /// Wipe everything after this many consecutive wrong unlock attempts (0 = off).
  int get wipeAfterAttempts => _wipeAfterAttempts;

  /// Attempts left before the wipe fires (or null if that protection is off).
  int? get attemptsRemaining => _wipeAfterAttempts > 0
      ? (_wipeAfterAttempts - _failedUnlocks).clamp(0, _wipeAfterAttempts)
      : null;

  /// Whether the session is currently locked (needs a re-unlock).
  bool get locked => _locked;

  Future<void> setAutoLockMinutes(int minutes) async {
    _autoLockMinutes = minutes;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_autoLockMinKey, minutes);
    notifyListeners();
  }

  Future<void> setLockOnBackground(bool on) async {
    _lockOnBackground = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_lockOnBgKey, on);
    notifyListeners();
  }

  Future<void> setWipeAfterAttempts(int n) async {
    _wipeAfterAttempts = n;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_wipeAttemptsKey, n);
    notifyListeners();
  }

  /// Re-lock the session: tear down the running engine and drop the seed from
  /// memory, so the password (vault) is needed again. No-op without an app
  /// password (there'd be nothing to unlock with) or if already locked.
  void lock() {
    if (!_passwordSet || _engine == null || _isDecoy) return;
    _pollTimer?.cancel();
    _coverTimer?.cancel();
    _cancelSyncWait();
    _engine = null;
    _seed = null;
    _node = null;
    _locked = true;
    notifyListeners();
  }

  Future<void> _resetFailedUnlocks() async {
    if (_failedUnlocks == 0) return;
    _failedUnlocks = 0;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_failedUnlocksKey, 0);
  }

  /// Count a wrong unlock; returns true if it tripped the wipe threshold (and
  /// the account was wiped).
  Future<bool> _recordFailedUnlock() async {
    _failedUnlocks += 1;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setInt(_failedUnlocksKey, _failedUnlocks);
    if (_wipeAfterAttempts > 0 && _failedUnlocks >= _wipeAfterAttempts) {
      await panicWipe();
      return true;
    }
    return false;
  }

  /// The current launcher disguise: `default`, `calculator`, `notes`, or
  /// `weather`.
  String get disguise => _disguise;

  /// Change the launcher disguise (icon + name). Persisted and applied
  /// immediately; the home-screen icon updates shortly after.
  Future<void> setDisguise(String which) async {
    _disguise = which;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_disguiseKey, which);
    await Disguise.apply(which);
    notifyListeners();
  }

  UpdateInfo? _update; // a newer GitHub release, if one is available

  /// A newer release, if the last check found one (null otherwise).
  UpdateInfo? get availableUpdate => _update;

  /// Ask GitHub whether a newer release exists; updates [availableUpdate] and
  /// notifies listeners if so. Safe to call repeatedly; never throws.
  Future<void> checkForUpdate() async {
    final u = await Updater.check();
    if (u != null) {
      _update = u;
      notifyListeners();
    }
  }

  /// Whether the app keeps receiving in the background (default on).
  bool get backgroundEnabled => _background;

  /// Turn 24/7 background operation on or off (persisted, applied immediately).
  Future<void> setBackgroundEnabled(bool on) async {
    _background = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_backgroundKey, on);
    if (on) {
      await BackgroundService.start();
    } else {
      await BackgroundService.stop();
    }
    notifyListeners();
  }

  /// Whether screenshots and screen recording are blocked (default on).
  bool get screenshotsBlocked => _secureScreen;

  /// Turn the screenshot / screen-recording block on or off (persisted, applied
  /// immediately).
  Future<void> setScreenshotsBlocked(bool on) async {
    _secureScreen = on;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_secureScreenKey, on);
    await ScreenSecurity.setSecure(on);
    notifyListeners();
  }

  /// What's stored at launch: none (→ onboarding), plaintext (→ boot directly),
  /// or locked (→ ask for the app password before booting).
  Future<AccountState> accountState() async {
    final prefs = await SharedPreferences.getInstance();
    if (prefs.getString(_vaultKey) != null) return AccountState.locked;
    // A no-password seed lives in the keystore now; a legacy plaintext one in
    // prefs still counts (it's migrated on boot).
    if (await SecureStore.hasSeed() || prefs.getString(_seedKey) != null) {
      return AccountState.plaintext;
    }
    return AccountState.none;
  }

  /// Boot from a keystore-held seed (no app password set). Migrates a legacy
  /// plaintext seed out of SharedPreferences into the keystore on first run.
  Future<void> bootPlaintext() async {
    final prefs = await SharedPreferences.getInstance();
    var seedHex = await SecureStore.readSeed();
    if (seedHex == null) {
      final legacy = prefs.getString(_seedKey);
      if (legacy != null) {
        await SecureStore.writeSeed(legacy);
        await prefs.remove(_seedKey);
        seedHex = legacy;
      }
    }
    if (seedHex == null) throw StateError('no seed saved');
    _passwordSet = false;
    _isDecoy = false;
    await _bootWithSeed(_decodeSeed(seedHex));
  }

  /// Decrypt the password vault and boot. Throws if the password matches neither
  /// the real nor the duress password — the seed never leaves Rust in plaintext,
  /// and there is no seed on disk to fall back to, so the lock cannot be
  /// bypassed.
  ///
  /// If a duress password is set and entered here, the **decoy** account boots
  /// instead: an empty, self-contained identity that looks like a normal (if
  /// unused) account, while the real one stays encrypted and hidden. Nothing
  /// signals to the caller which account opened.
  Future<void> unlock(String password) async {
    await _ensureRustInit();
    final prefs = await SharedPreferences.getInstance();
    final b64 = prefs.getString(_vaultKey);
    if (b64 == null) throw StateError('no vault');
    // Try the real vault first.
    try {
      final seed = await openSeed(password: password, blob: base64Decode(b64));
      _passwordSet = true;
      _isDecoy = false;
      _locked = false;
      await _resetFailedUnlocks();
      await _bootWithSeed(Uint8List.fromList(seed));
      return;
    } catch (_) {
      // Not the real password — fall through to the duress vault.
    }
    // A matching duress password opens the decoy account.
    final d64 = prefs.getString(_duressVaultKey);
    if (d64 != null) {
      try {
        final seed = await openSeed(password: password, blob: base64Decode(d64));
        _passwordSet = true;
        _locked = false;
        await _resetFailedUnlocks();
        await _bootDecoy(Uint8List.fromList(seed));
        return;
      } catch (_) {
        // Not the duress password either — fall through to the failure path.
      }
    }
    // Neither vault opened: a wrong password. Count it, and wipe if the limit
    // is reached.
    final wiped = await _recordFailedUnlock();
    if (wiped) throw AccountWipedException();
    throw StateError('wrong password');
  }

  /// Set (or change) the app-lock password: encrypt the in-memory seed under it,
  /// store only the vault, and delete the plaintext seed. The engine must be
  /// running (unlocked) so we hold the seed.
  Future<void> setAppPassword(String password) async {
    if (_isDecoy) throw StateError('not available in the decoy account');
    final seed = _seed;
    if (seed == null) throw StateError('no seed loaded');
    final blob = await sealSeed(password: password, seed: seed);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_vaultKey, base64Encode(blob));
    await prefs.remove(_seedKey); // clear any legacy plaintext seed
    await SecureStore.clear(); // seed now lives only in the password vault
    _passwordSet = true;
    notifyListeners();
  }

  /// Remove the app-lock password: move the seed into keystore-backed storage
  /// (still not plaintext on disk) and drop the vault. Requires the engine to be
  /// running (unlocked).
  Future<void> removeAppPassword() async {
    if (_isDecoy) throw StateError('not available in the decoy account');
    final seed = _seed;
    if (seed == null) throw StateError('no seed loaded');
    final prefs = await SharedPreferences.getInstance();
    await SecureStore.writeSeed(_encodeSeed(seed));
    await prefs.remove(_seedKey); // never leave a plaintext copy behind
    await prefs.remove(_vaultKey);
    _passwordSet = false;
    // Biometric unlock is layered over the password; without a password it makes
    // no sense, so drop the stored biometric seed too.
    await Biometrics.clear();
    notifyListeners();
  }

  // --- biometric unlock -----------------------------------------------------

  /// Whether this device has biometric hardware with an enrolled fingerprint or
  /// face.
  Future<bool> biometricDeviceSupported() => Biometrics.deviceSupported();

  /// Whether biometric unlock is currently enabled (a seed is stored for it).
  Future<bool> biometricEnabled() => Biometrics.hasStoredSeed();

  /// Enable biometric unlock: copy the running identity's seed into
  /// Keystore-backed secure storage so a fingerprint/face check can boot it
  /// without the password. Requires an app-lock password and the real account
  /// unlocked (not the decoy).
  Future<void> enableBiometric() async {
    if (_isDecoy) throw StateError('not available in the decoy account');
    if (!_passwordSet) {
      throw StateError('set an app-lock password before biometric unlock');
    }
    final seed = _seed;
    if (seed == null) throw StateError('no seed loaded');
    if (!await Biometrics.deviceSupported()) {
      throw StateError('no enrolled fingerprint or face on this device');
    }
    await Biometrics.storeSeed(seed);
    notifyListeners();
  }

  /// Disable biometric unlock and erase the seed held for it.
  Future<void> disableBiometric() async {
    await Biometrics.clear();
    notifyListeners();
  }

  /// Unlock with a biometric check instead of the password: prompt, and on a
  /// successful match read the stored seed and boot the real account. Returns
  /// false if biometrics aren't set up, the check fails, or the seed is missing
  /// (fall back to the password). Never bypasses anything without a live
  /// fingerprint/face match.
  Future<bool> unlockWithBiometric() async {
    if (!await Biometrics.hasStoredSeed()) return false;
    if (!await Biometrics.authenticate('Unlock Aegis')) return false;
    final seed = await Biometrics.readSeed();
    if (seed == null) return false;
    await _ensureRustInit();
    _passwordSet = true;
    _isDecoy = false;
    await _bootWithSeed(seed);
    return true;
  }

  /// Set (or change) the duress/decoy password. A fresh random seed is minted
  /// for the decoy and sealed under [password]; entering it at the lock screen
  /// opens that empty account instead of the real one. Requires an app-lock
  /// password to be set (duress works through the lock screen) and the real
  /// account to be running — not available in the decoy itself.
  ///
  /// Choose a duress password **different** from the real one; if they match,
  /// the real vault always opens first and the decoy is never reached.
  Future<void> setDuressPassword(String password) async {
    if (_isDecoy) throw StateError('not available in the decoy account');
    if (!_passwordSet) {
      throw StateError('set an app-lock password before a duress password');
    }
    final decoySeed = _randomSeed();
    final blob = await sealSeed(password: password, seed: decoySeed);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_duressVaultKey, base64Encode(blob));
    await prefs.remove(_decoyStateKey); // a fresh decoy has no history
    _hasDuress = true;
    notifyListeners();
  }

  /// Remove the duress/decoy password and discard the decoy account's data.
  Future<void> removeDuressPassword() async {
    if (_isDecoy) throw StateError('not available in the decoy account');
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_duressVaultKey);
    await prefs.remove(_decoyStateKey);
    _hasDuress = false;
    notifyListeners();
  }

  /// Panic wipe: instantly and irreversibly destroy the account's data and tear
  /// down the engine. Meant for a hold-to-confirm button the user can hit under
  /// pressure.
  ///
  /// From the **real** account this erases everything — seed, both vaults,
  /// state, node settings — leaving the device at onboarding. From the **decoy**
  /// account it clears only the decoy's data, so an attacker who finds and hits
  /// the button never destroys (or learns of) the real account.
  Future<void> panicWipe() async {
    final decoyOnly = _isDecoy;
    _pollTimer?.cancel();
    _coverTimer?.cancel();
    _cancelSyncWait();
    final prefs = await SharedPreferences.getInstance();
    if (decoyOnly) {
      await prefs.remove(_decoyStateKey);
      await prefs.remove(_decoyNotesKey);
    } else {
      await prefs.remove(_seedKey);
      await SecureStore.clear();
      await prefs.remove(_vaultKey);
      await prefs.remove(_duressVaultKey);
      await prefs.remove(_stateKey);
      await prefs.remove(_decoyStateKey);
      await prefs.remove(_notesKey);
      await prefs.remove(_decoyNotesKey);
      await prefs.remove(_modeKey);
      await prefs.remove(_nodeVerifiedKey);
      await prefs.remove(_nodeKey);
      await prefs.remove(_notifyKey);
      await prefs.remove(_favNodesKey);
      await Biometrics.clear();
    }
    _engine = null;
    _node = null;
    _seed = null;
    _nodeEnabled = false;
    _anonReceive = false;
    _passwordSet = false;
    _nodeVerified = false;
    _hasDuress = false;
    _isDecoy = false;
    // No notifyListeners: the caller navigates away to onboarding/lock and drops
    // the screens that read engine state.
  }

  /// Bring the engine up from a decrypted [seed] and restore saved state.
  Future<void> _bootWithSeed(Uint8List seed) async {
    final prefs = await SharedPreferences.getInstance();
    _isDecoy = false;
    _hasDuress = prefs.getString(_duressVaultKey) != null;
    _mode = prefs.getString(_modeKey) ?? 'network';
    _userBootstrap = prefs.getStringList(_bootstrapKey) ?? const [];
    _ownNodesOnly = prefs.getBool(_ownNodesOnlyKey) ?? false;
    _favNodes = (prefs.getStringList(_favNodesKey) ?? const []).toSet();
    _notify = prefs.getBool(_notifyKey) ?? false;
    await _start(seed);
    // Restore sessions, contacts, and history saved on the last run.
    final blob = prefs.getString(_stateKey);
    if (blob != null) {
      try {
        _engine!.restoreStateEncrypted(blob: base64Decode(blob));
      } catch (e) {
        debugPrint('state restore failed (starting fresh): $e');
      }
    }
    await _restoreNotes();
    // Resume node mode (defaults per platform on first run).
    _nodeVerified = prefs.getBool(_nodeVerifiedKey) ?? false;
    _nodeEnabled = prefs.getBool(_nodeKey) ?? kNodeDefaultOn;
    if (_nodeEnabled) {
      await _startNode();
      // An unverified node that resumes must complete the sync wait again (it
      // was down while the app was closed).
      if (!_nodeVerified) _startSyncWait();
    }
  }

  /// Bring up the decoy account: a working but empty identity that boots on the
  /// network like a normal account. It uses its own state store, never runs a
  /// node, and never touches the real account's seed, vault, or state.
  Future<void> _bootDecoy(Uint8List seed) async {
    final prefs = await SharedPreferences.getInstance();
    _isDecoy = true;
    _hasDuress = true; // by definition, we got here via the duress vault
    _mode = 'network';
    _userBootstrap = prefs.getStringList(_bootstrapKey) ?? const [];
    _ownNodesOnly = prefs.getBool(_ownNodesOnlyKey) ?? false;
    _favNodes = {};
    _notify = false;
    _nodeEnabled = false;
    _nodeVerified = false;
    await _start(seed);
    // Restore the decoy's own history, if it has been used before.
    final blob = prefs.getString(_decoyStateKey);
    if (blob != null) {
      try {
        _engine!.restoreStateEncrypted(blob: base64Decode(blob));
      } catch (e) {
        debugPrint('decoy state restore failed (starting fresh): $e');
      }
    }
    await _restoreNotes();
  }

  /// Create a brand-new identity from fresh randomness and persist the seed.
  /// [mode] picks how it connects; [relayAddr] is required for [ConnMode.relay].
  Future<void> createIdentity({
    ConnMode mode = ConnMode.network,
    String? relayAddr,
    List<String> bootstrap = const [],
  }) async {
    final seed = _randomSeed();
    _mode = switch (mode) {
      ConnMode.network => 'network',
      ConnMode.relay => 'relay:${relayAddr ?? ''}',
      ConnMode.memory => 'memory',
    };
    final prefs = await SharedPreferences.getInstance();
    if (bootstrap.isNotEmpty) {
      _userBootstrap = bootstrap;
      await prefs.setStringList(_bootstrapKey, bootstrap);
    }
    await SecureStore.writeSeed(_encodeSeed(seed));
    await prefs.setString(_modeKey, _mode);
    await prefs.remove(_stateKey); // a fresh identity has no prior sessions
    await _start(seed);
    _nodeEnabled = prefs.getBool(_nodeKey) ?? kNodeDefaultOn;
    if (_nodeEnabled) await _startNode();
  }

  /// The 24-word recovery phrase for this device's identity. Write it down to
  /// restore the same Aegis ID on another device. Requires the engine to be
  /// running (unlocked).
  String recoveryPhrase() {
    final seed = _seed;
    if (seed == null) throw StateError('no seed loaded');
    return seedToPhrase(seed: seed);
  }

  /// Restore an identity from a 24-word recovery phrase (same seed → same Aegis
  /// ID). Throws if the phrase is invalid. The restored account starts with no
  /// local message history — the phrase backs up the identity, not the chats.
  Future<void> restoreFromMnemonic(
    String phrase, {
    ConnMode mode = ConnMode.network,
    String? relayAddr,
    List<String> bootstrap = const [],
  }) async {
    final seed = phraseToSeed(phrase: phrase.trim());
    _mode = switch (mode) {
      ConnMode.network => 'network',
      ConnMode.relay => 'relay:${relayAddr ?? ''}',
      ConnMode.memory => 'memory',
    };
    final prefs = await SharedPreferences.getInstance();
    if (bootstrap.isNotEmpty) {
      _userBootstrap = bootstrap;
      await prefs.setStringList(_bootstrapKey, bootstrap);
    }
    await SecureStore.writeSeed(_encodeSeed(seed));
    await prefs.setString(_modeKey, _mode);
    await prefs.remove(_stateKey);
    await _start(seed);
    _nodeEnabled = prefs.getBool(_nodeKey) ?? kNodeDefaultOn;
    if (_nodeEnabled) await _startNode();
  }

  Future<void> _start(Uint8List seed) async {
    _seed = seed;
    // In network mode with node mode on, run our own node and receive
    // anonymously through it (the provider never learns we are polling). The
    // network/relay constructors are async (they connect + discover); in-memory
    // is synchronous.
    _anonReceive = _mode == 'network' && _nodeEnabled;
    if (_mode == 'network') {
      _engine = _anonReceive
          ? await AegisEngine.newOnNetworkWithReceive(
              masterSeed: seed, bootstrap: _bootstrap, nodeListen: '0.0.0.0:0')
          : await AegisEngine.newOnNetwork(masterSeed: seed, bootstrap: _bootstrap);
    } else if (_mode.startsWith('relay:')) {
      _engine =
          await AegisEngine.newWithRelay(masterSeed: seed, relayAddr: _mode.substring(6));
    } else {
      _engine = AegisEngine.newInMemory(masterSeed: seed);
    }
    _pollTimer?.cancel();
    _pollTimer = Timer.periodic(const Duration(seconds: 3), (_) => _poll());
    // On the mixnet, emit cover traffic on a Poisson schedule so an observer
    // can't tell real sends from silence.
    _coverTimer?.cancel();
    if (_mode == 'network') _scheduleCover();
    notifyListeners();
  }

  /// Schedule the next cover packet after an Exp(mean 45s) delay, then repeat.
  void _scheduleCover() {
    final u = 1.0 - _rng.nextDouble(); // (0,1]
    final secs = (-log(u) * 45).clamp(2.0, 600.0);
    _coverTimer = Timer(Duration(milliseconds: (secs * 1000).round()), () {
      try {
        _engine?.sendCover();
      } catch (_) {}
      _scheduleCover();
    });
  }

  /// Turn opt-in node mode on or off (persisted). On desktop/Linux this both
  /// carries others' traffic and (in network mode) enables anonymous receive.
  ///
  /// Enabling requires a **publicly reachable IP** — a device with only a
  /// local/private/loopback address can't be a node, so we refuse and throw
  /// [NodeModeError]. The first time, the node must then stay up for
  /// [nodeSyncDuration] ("synchronizing") to be verified; after that it toggles
  /// instantly.
  Future<void> setNodeEnabled(bool enabled) async {
    if (enabled) {
      final ip = await _publicIp();
      if (ip == null) {
        throw NodeModeError(
          'This device has only a local or private IP address, so other people '
          'can’t reach it as a node. Enable node mode where the device has a '
          'public address (a server, or with a forwarded port).',
        );
      }
    }
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_nodeKey, enabled);
    _nodeEnabled = enabled;
    // In network mode the node is baked into the engine, so rebuild it to switch
    // anonymous receive on/off, restoring saved state.
    if (_mode == 'network' && _seed != null) {
      await _start(_seed!);
      final blob = prefs.getString(_activeStateKey);
      if (blob != null) {
        try {
          _engine!.restoreStateEncrypted(blob: base64Decode(blob));
        } catch (_) {}
      }
    } else if (enabled) {
      await _startNode();
    } else {
      _node = null;
    }
    // Verification: a first-time enable starts the sync wait; disabling before
    // it finishes cancels it (stays unverified).
    if (enabled && !_nodeVerified) {
      _startSyncWait();
    } else if (!enabled) {
      _cancelSyncWait();
    }
    notifyListeners();
  }

  void _startSyncWait() {
    _syncTimer?.cancel();
    _syncCompleteAt = DateTime.now().add(nodeSyncDuration);
    _syncTimer = Timer.periodic(const Duration(seconds: 20), (t) async {
      if (_syncCompleteAt == null ||
          !DateTime.now().isBefore(_syncCompleteAt!)) {
        t.cancel();
        _syncTimer = null;
        _syncCompleteAt = null;
        _nodeVerified = true;
        final prefs = await SharedPreferences.getInstance();
        await prefs.setBool(_nodeVerifiedKey, true);
      }
      notifyListeners();
    });
  }

  void _cancelSyncWait() {
    _syncTimer?.cancel();
    _syncTimer = null;
    _syncCompleteAt = null;
  }

  /// This device's first public (non-private, non-loopback) IPv4, or null if it
  /// has only local addresses.
  Future<String?> _publicIp() async {
    try {
      final ifaces = await NetworkInterface.list(
        type: InternetAddressType.IPv4,
        includeLoopback: false,
      );
      for (final iface in ifaces) {
        for (final a in iface.addresses) {
          if (!_isLocalIp(a.address)) return a.address;
        }
      }
    } catch (_) {}
    return null;
  }

  static bool _isLocalIp(String ip) {
    if (ip == '0.0.0.0' ||
        ip == 'localhost' ||
        ip.startsWith('127.') ||
        ip.startsWith('169.254.') || // link-local
        ip.startsWith('10.') ||
        ip.startsWith('192.168.')) {
      return true;
    }
    final m = RegExp(r'^172\.(\d{1,3})\.').firstMatch(ip);
    if (m != null) {
      final o = int.tryParse(m.group(1)!) ?? 0;
      if (o >= 16 && o <= 31) return true; // 172.16/12 private range
    }
    return false;
  }

  /// Wipe this device's identity: forget the master seed and all saved state
  /// (sessions, contacts, history) and tear down the engine. The next screen
  /// should be onboarding, where a fresh identity is minted. Irreversible —
  /// there is no key escrow, so the old identity and its history are gone.
  Future<void> resetIdentity() async {
    // From the decoy, a "reset" must not touch the real account — scope it to
    // the decoy's own data (same rule as a decoy panic wipe).
    if (_isDecoy) return panicWipe();
    _pollTimer?.cancel();
    _coverTimer?.cancel();
    _cancelSyncWait();
    _nodeVerified = false;
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_seedKey);
    await SecureStore.clear();
    await prefs.remove(_vaultKey);
    await prefs.remove(_duressVaultKey);
    await prefs.remove(_stateKey);
    await prefs.remove(_decoyStateKey);
    await prefs.remove(_notesKey);
    await prefs.remove(_decoyNotesKey);
    await prefs.remove(_modeKey);
    await prefs.remove(_nodeVerifiedKey);
    await prefs.remove(_nodeKey);
    await Biometrics.clear();
    _engine = null;
    _node = null;
    _seed = null;
    _nodeEnabled = false;
    _anonReceive = false;
    _passwordSet = false;
    _hasDuress = false;
    _isDecoy = false;
    // No notifyListeners: the caller navigates to onboarding and drops the
    // screens that read engine state, so a rebuild here would only risk a
    // transient null read.
  }

  Future<void> _startNode() async {
    // A standalone forwarder for non-network modes (network mode runs its node
    // inside the engine via anonymous receive).
    if (_anonReceive) return;
    try {
      _node = await startForwarderNode(
        bootstrap: _bootstrap,
        listen: '0.0.0.0:0',
        delayRate: null,
      );
    } catch (e) {
      debugPrint('node start failed: $e');
      _nodeEnabled = false;
    }
  }

  List<Contact> contacts() => _engine?.contacts() ?? const [];

  List<ChatMessage> history(String aegisId) =>
      _engine?.history(aegisId: aegisId) ?? const [];

  /// The safety number to compare with a contact out of band (MITM check).
  String safetyNumber(String aegisId) =>
      _engine!.safetyNumber(aegisId: aegisId);

  void addContact({
    required String name,
    required String aegisId,
    required Uint8List bundle,
  }) {
    _engine!.addContact(name: name, aegisId: aegisId, bundle: bundle);
    _persist();
    notifyListeners();
  }

  Future<void> send({required String aegisId, required String text}) async {
    await _engine!.send(aegisId: aegisId, text: text);
    _persist();
    notifyListeners();
  }

  /// Retry a message whose earlier send failed (shown with a failed marker).
  Future<void> resend({required String aegisId, required BigInt id}) async {
    await _engine?.resend(aegisId: aegisId, id: id);
    _persist();
    notifyListeners();
  }

  /// Pin or unpin a chat (pinned chats sort to the top of the list).
  Future<void> setPinned(String aegisId, bool pinned) async {
    await _engine?.setPinned(aegisId: aegisId, pinned: pinned);
    _persist();
    notifyListeners();
  }

  /// Block or unblock a contact (a blocked contact's messages are dropped).
  Future<void> setBlocked(String aegisId, bool blocked) async {
    await _engine?.setBlocked(aegisId: aegisId, blocked: blocked);
    _persist();
    notifyListeners();
  }

  /// Move a chat one place up or down within its pinned group.
  Future<void> moveChat(String aegisId, {required bool up}) async {
    await _engine?.moveChat(aegisId: aegisId, up: up);
    _persist();
    notifyListeners();
  }

  /// Delete a conversation on this device only.
  Future<void> deleteChat(String aegisId) async {
    await _engine?.deleteChat(aegisId: aegisId);
    _persist();
    notifyListeners();
  }

  /// Delete a conversation for both sides (asks the peer to delete it too).
  Future<void> deleteChatForBoth(String aegisId) async {
    await _engine?.deleteChatForBoth(aegisId: aegisId);
    _persist();
    notifyListeners();
  }

  /// Mark the conversation as read so read receipts go to the sender. Call when
  /// the user is looking at the chat. Best-effort (fire-and-forget); the engine
  /// only sends a receipt once per message.
  void markRead(String aegisId) {
    _engine?.markRead(aegisId: aegisId);
  }

  /// The disappearing-message timer for a chat, in seconds (0 = off).
  int disappearingSecs(String aegisId) =>
      _engine?.disappearingSecs(aegisId: aegisId) ?? 0;

  /// Set the disappearing-message timer for a chat (0 = off); synced to the peer.
  void setDisappearing(String aegisId, int secs) {
    _engine?.setDisappearing(aegisId: aegisId, secs: secs);
    notifyListeners();
  }

  Future<void> _poll() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final res = await engine.poll();
      if (res.messages.isNotEmpty && _notify) {
        for (final m in res.messages) {
          Notifications.showMessage(
            title: m.fromName ?? 'New message',
            id: m.fromAegisId.hashCode,
          );
        }
      }
      // Only touch disk and rebuild the UI when something actually changed
      // (new message, a receipt advancing a tick, a timer/delete, a retry
      // landing). An idle poll is now free — no lag from 3-second rebuilds.
      if (res.changed) {
        _persist();
        notifyListeners();
      }
    } catch (e) {
      // Relay unreachable — stay quiet; the next tick retries.
      debugPrint('poll failed: $e');
    }
  }

  /// Save the engine's state (sessions, contacts, history) so the next launch
  /// resumes where this one left off. Fire-and-forget; a missed save just means
  /// the last few messages re-sync from the relay.
  Future<void> _persist() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final blob = engine.exportStateEncrypted();
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_activeStateKey, base64Encode(blob));
    } catch (e) {
      debugPrint('state save failed: $e');
    }
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    _coverTimer?.cancel();
    _syncTimer?.cancel();
    super.dispose();
  }

  // --- seed helpers ---------------------------------------------------------

  static Uint8List _randomSeed() {
    final rng = Random.secure();
    return Uint8List.fromList(List.generate(32, (_) => rng.nextInt(256)));
  }

  static String _encodeSeed(Uint8List seed) =>
      seed.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

  static Uint8List _decodeSeed(String hex) {
    final out = Uint8List(hex.length ~/ 2);
    for (var i = 0; i < out.length; i++) {
      out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
    }
    return out;
  }
}
