import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Generated by `flutter_rust_bridge_codegen generate` (see
// flutter_rust_bridge.yaml). These files do not exist until you run codegen.
import 'src/rust/api/aegis.dart';
import 'src/rust/frb_generated.dart';

import 'config.dart';

const _seedKey = 'aegis.master_seed';
const _modeKey = 'aegis.mode'; // 'network' | 'relay:<addr>' | 'memory'
const _stateKey = 'aegis.state_blob'; // base64 sessions + contacts + history
const _nodeKey = 'aegis.node_enabled';
const _bootstrapKey = 'aegis.bootstrap'; // comma-separated user-added nodes

/// How this device reaches the network.
enum ConnMode { network, relay, memory }

/// Owns the one Rust [AegisEngine] and the app's chat state. Screens listen to
/// this and call into it; the seed lives in [SharedPreferences] and all crypto
/// stays in Rust.
class AegisEngineController extends ChangeNotifier {
  AegisEngine? _engine;
  Timer? _pollTimer;
  String _mode = 'network';
  bool _nodeEnabled = false;
  NodeInfo? _node;
  List<String> _userBootstrap = const [];
  Uint8List? _seed; // kept in memory to rebuild the engine on a node toggle
  bool _anonReceive = false; // network + node mode: the engine runs its own node

  /// The bootstrap nodes actually used: any compiled in (`--dart-define`) plus
  /// any the user added, de-duplicated.
  List<String> get _bootstrap =>
      {...kBootstrapNodes, ..._userBootstrap}.toList();

  /// Whether the app knows any node to bootstrap from (else it can't use the
  /// mixnet and the user must add one).
  bool get hasBootstrap => _bootstrap.isNotEmpty;

  bool get isReady => _engine != null;
  String get myAegisId => _engine!.myAegisId();
  Uint8List get myBundle => _engine!.myBundle();

  /// Whether this device is also running an opt-in mix node.
  bool get nodeEnabled => _nodeEnabled;

  /// The running node's address + id, if node mode is on.
  NodeInfo? get node => _node;

  /// Whether receive is going through the mixnet (anonymous), not a direct poll.
  bool get anonReceive => _anonReceive;

  /// A human label for the current connection mode.
  String get connectionLabel {
    if (_mode == 'network') {
      return _anonReceive
          ? 'Mixnet · anonymous send + receive'
          : 'Mixnet · anonymous send';
    }
    if (_mode.startsWith('relay:')) return 'Relay ${_mode.substring(6)}';
    return 'Offline (in-memory)';
  }

  /// Initialize the bridge and, if a seed was saved, restore the engine.
  /// Returns true if an engine is now live (existing account).
  Future<bool> boot() async {
    await RustLib.init();
    final prefs = await SharedPreferences.getInstance();
    final seed = prefs.getString(_seedKey);
    if (seed == null) return false;
    _mode = prefs.getString(_modeKey) ?? 'network';
    _userBootstrap = prefs.getStringList(_bootstrapKey) ?? const [];
    _start(_decodeSeed(seed));
    // Restore sessions, contacts, and history saved on the last run.
    final blob = prefs.getString(_stateKey);
    if (blob != null) {
      try {
        _engine!.restoreState(blob: base64Decode(blob));
      } catch (e) {
        debugPrint('state restore failed (starting fresh): $e');
      }
    }
    // Resume node mode (defaults per platform on first run).
    _nodeEnabled = prefs.getBool(_nodeKey) ?? kNodeDefaultOn;
    if (_nodeEnabled) _startNode();
    return true;
  }

  /// Create a brand-new identity from fresh randomness and persist the seed.
  /// [mode] picks how it connects; [relayAddr] is required for [ConnMode.relay].
  Future<void> createIdentity({
    ConnMode mode = ConnMode.network,
    String? relayAddr,
    List<String> bootstrap = const [],
  }) async {
    final seed = _randomSeed();
    _mode = switch (mode) {
      ConnMode.network => 'network',
      ConnMode.relay => 'relay:${relayAddr ?? ''}',
      ConnMode.memory => 'memory',
    };
    final prefs = await SharedPreferences.getInstance();
    if (bootstrap.isNotEmpty) {
      _userBootstrap = bootstrap;
      await prefs.setStringList(_bootstrapKey, bootstrap);
    }
    await prefs.setString(_seedKey, _encodeSeed(seed));
    await prefs.setString(_modeKey, _mode);
    await prefs.remove(_stateKey); // a fresh identity has no prior sessions
    _start(seed);
    _nodeEnabled = prefs.getBool(_nodeKey) ?? kNodeDefaultOn;
    if (_nodeEnabled) _startNode();
  }

  void _start(Uint8List seed) {
    _seed = seed;
    // In network mode with node mode on, run our own node and receive
    // anonymously through it (the provider never learns we are polling).
    _anonReceive = _mode == 'network' && _nodeEnabled;
    _engine = switch (_mode) {
      'network' when _anonReceive => AegisEngine.newOnNetworkWithReceive(
          masterSeed: seed, bootstrap: _bootstrap, nodeListen: '0.0.0.0:0'),
      'network' => AegisEngine.newOnNetwork(masterSeed: seed, bootstrap: _bootstrap),
      _ when _mode.startsWith('relay:') =>
        AegisEngine.newWithRelay(masterSeed: seed, relayAddr: _mode.substring(6)),
      _ => AegisEngine.newInMemory(masterSeed: seed),
    };
    _pollTimer?.cancel();
    _pollTimer = Timer.periodic(const Duration(seconds: 3), (_) => _poll());
    notifyListeners();
  }

  /// Turn opt-in node mode on or off (persisted). On desktop/Linux this both
  /// carries others' traffic and (in network mode) enables anonymous receive.
  Future<void> setNodeEnabled(bool enabled) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_nodeKey, enabled);
    _nodeEnabled = enabled;
    // In network mode the node is baked into the engine, so rebuild it to switch
    // anonymous receive on/off, restoring saved state.
    if (_mode == 'network' && _seed != null) {
      _start(_seed!);
      final blob = prefs.getString(_stateKey);
      if (blob != null) {
        try {
          _engine!.restoreState(blob: base64Decode(blob));
        } catch (_) {}
      }
    } else if (enabled) {
      _startNode();
    } else {
      _node = null;
    }
    notifyListeners();
  }

  void _startNode() {
    // A standalone forwarder for non-network modes (network mode runs its node
    // inside the engine via anonymous receive).
    if (_anonReceive) return;
    try {
      _node = startForwarderNode(
        bootstrap: _bootstrap,
        listen: '0.0.0.0:0',
        delayRate: null,
      );
    } catch (e) {
      debugPrint('node start failed: $e');
      _nodeEnabled = false;
    }
  }

  List<Contact> contacts() => _engine?.contacts() ?? const [];

  List<ChatMessage> history(String aegisId) =>
      _engine?.history(aegisId: aegisId) ?? const [];

  void addContact({
    required String name,
    required String aegisId,
    required Uint8List bundle,
  }) {
    _engine!.addContact(name: name, aegisId: aegisId, bundle: bundle);
    _persist();
    notifyListeners();
  }

  void send({required String aegisId, required String text}) {
    _engine!.send(aegisId: aegisId, text: text);
    _persist();
    notifyListeners();
  }

  Future<void> _poll() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final incoming = await engine.poll();
      if (incoming.isNotEmpty) {
        _persist();
        notifyListeners();
      }
    } catch (e) {
      // Relay unreachable — stay quiet; the next tick retries.
      debugPrint('poll failed: $e');
    }
  }

  /// Save the engine's state (sessions, contacts, history) so the next launch
  /// resumes where this one left off. Fire-and-forget; a missed save just means
  /// the last few messages re-sync from the relay.
  Future<void> _persist() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final blob = engine.exportState();
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_stateKey, base64Encode(blob));
    } catch (e) {
      debugPrint('state save failed: $e');
    }
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

  // --- seed helpers ---------------------------------------------------------

  static Uint8List _randomSeed() {
    final rng = Random.secure();
    return Uint8List.fromList(List.generate(32, (_) => rng.nextInt(256)));
  }

  static String _encodeSeed(Uint8List seed) =>
      seed.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

  static Uint8List _decodeSeed(String hex) {
    final out = Uint8List(hex.length ~/ 2);
    for (var i = 0; i < out.length; i++) {
      out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
    }
    return out;
  }
}
