import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Generated by `flutter_rust_bridge_codegen generate` (see
// flutter_rust_bridge.yaml). These files do not exist until you run codegen.
import 'src/rust/api/aegis.dart';
import 'src/rust/frb_generated.dart';

const _seedKey = 'aegis.master_seed';
const _relayKey = 'aegis.relay_addr';
const _stateKey = 'aegis.state_blob'; // base64 sessions + contacts + history

/// Owns the one Rust [AegisEngine] and the app's chat state. Screens listen to
/// this and call into it; the seed lives in [SharedPreferences] and all crypto
/// stays in Rust.
class AegisEngineController extends ChangeNotifier {
  AegisEngine? _engine;
  Timer? _pollTimer;
  String? _relayAddr;

  bool get isReady => _engine != null;
  String get myAegisId => _engine!.myAegisId();
  Uint8List get myBundle => _engine!.myBundle();
  String? get relayAddr => _relayAddr;

  /// Initialize the bridge and, if a seed was saved, restore the engine.
  /// Returns true if an engine is now live (existing account).
  Future<bool> boot() async {
    await RustLib.init();
    final prefs = await SharedPreferences.getInstance();
    final seed = prefs.getString(_seedKey);
    if (seed == null) return false;
    _relayAddr = prefs.getString(_relayKey);
    _start(_decodeSeed(seed), _relayAddr);
    // Restore sessions, contacts, and history saved on the last run.
    final blob = prefs.getString(_stateKey);
    if (blob != null) {
      try {
        _engine!.restoreState(blob: base64Decode(blob));
      } catch (e) {
        debugPrint('state restore failed (starting fresh): $e');
      }
    }
    return true;
  }

  /// Create a brand-new identity from fresh randomness and persist the seed.
  /// `relayAddr` null → local in-memory relay (offline demo).
  Future<void> createIdentity({String? relayAddr}) async {
    final seed = _randomSeed();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_seedKey, _encodeSeed(seed));
    await prefs.remove(_stateKey); // a fresh identity has no prior sessions
    if (relayAddr != null && relayAddr.isNotEmpty) {
      await prefs.setString(_relayKey, relayAddr);
    } else {
      await prefs.remove(_relayKey);
    }
    _relayAddr = relayAddr;
    _start(seed, relayAddr);
  }

  void _start(Uint8List seed, String? relayAddr) {
    _engine = (relayAddr != null && relayAddr.isNotEmpty)
        ? AegisEngine.newWithRelay(masterSeed: seed, relayAddr: relayAddr)
        : AegisEngine.newInMemory(masterSeed: seed);
    _pollTimer?.cancel();
    _pollTimer = Timer.periodic(const Duration(seconds: 3), (_) => _poll());
    notifyListeners();
  }

  List<Contact> contacts() => _engine?.contacts() ?? const [];

  List<ChatMessage> history(String aegisId) =>
      _engine?.history(aegisId: aegisId) ?? const [];

  void addContact({
    required String name,
    required String aegisId,
    required Uint8List bundle,
  }) {
    _engine!.addContact(name: name, aegisId: aegisId, bundle: bundle);
    _persist();
    notifyListeners();
  }

  void send({required String aegisId, required String text}) {
    _engine!.send(aegisId: aegisId, text: text);
    _persist();
    notifyListeners();
  }

  Future<void> _poll() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final incoming = await engine.poll();
      if (incoming.isNotEmpty) {
        _persist();
        notifyListeners();
      }
    } catch (e) {
      // Relay unreachable — stay quiet; the next tick retries.
      debugPrint('poll failed: $e');
    }
  }

  /// Save the engine's state (sessions, contacts, history) so the next launch
  /// resumes where this one left off. Fire-and-forget; a missed save just means
  /// the last few messages re-sync from the relay.
  Future<void> _persist() async {
    final engine = _engine;
    if (engine == null) return;
    try {
      final blob = engine.exportState();
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(_stateKey, base64Encode(blob));
    } catch (e) {
      debugPrint('state save failed: $e');
    }
  }

  @override
  void dispose() {
    _pollTimer?.cancel();
    super.dispose();
  }

  // --- seed helpers ---------------------------------------------------------

  static Uint8List _randomSeed() {
    final rng = Random.secure();
    return Uint8List.fromList(List.generate(32, (_) => rng.nextInt(256)));
  }

  static String _encodeSeed(Uint8List seed) =>
      seed.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

  static Uint8List _decodeSeed(String hex) {
    final out = Uint8List(hex.length ~/ 2);
    for (var i = 0; i < out.length; i++) {
      out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
    }
    return out;
  }
}
